name: az_functions
channels:
  - pkgs/main
dependencies:
  - python=3.10
  - pip
  - pip:
      # Dev
      - black
      - flake8
      - ipykernel
      - notebook
      - pydocstyle
      - pylint
      # App
      - azure-appconfiguration==1.4.0
      - azure-common==1.1.28
      - azure-core==1.27.0
      - azure-functions==1.14.0
      - azure-identity==1.13.0
      - azure-keyvault-secrets==4.7.0
      - azure-storage-blob==12.16.0
      - azure-storage-file-datalake==12.11.0
      - msal==1.22.0
      - numpy==1.24.3
      - numpyencoder==0.3.0
      - pandas==2.0.2
      - pyodbc==4.0.39
      - pylint-sqlalchemy==0.2.0
      - ratelimit==2.2.1
      - retrying==1.3.4
      - SQLAlchemy==2.0.15
