version: '3.8'

services:
  pyfapp:
    image: acrapp.azurecr.io/${BRANCH}/pyfapp:${TAG}
    container_name: pyfapp
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        TAG_NAME: ${TAG}
    ports:
      - 7071:80
    environment:
      - APPCF_ENDPOINT=${APPCF_ENDPOINT}
      - ENV_STATE=${ENV}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - APP_ROOT=${APP_ROOT}
